import type { AppSnapshot } from "../export/exportSnapshot";
import { DEFAULT_PREFERENCES } from "../constants";

export const demoSnapshot: AppSnapshot = {
  exportedAt: "2026-04-24T09:00:00.000Z",
  focusRefs: [
    {
      addedAt: "2026-04-24T10:00:00.000Z",
      order: 0,
      taskId: "task-long-title",
    },
    {
      addedAt: "2026-04-24T10:01:00.000Z",
      order: 1,
      taskId: "task-blocked",
    },
    {
      addedAt: "2026-04-24T10:02:00.000Z",
      order: 2,
      taskId: "task-complete",
    },
    {
      addedAt: "2026-04-28T10:03:00.000Z",
      order: 3,
      taskId: "task-polish-focus-card",
    },
    {
      addedAt: "2026-04-28T10:04:00.000Z",
      order: 4,
      taskId: "task-data-storage-consistency",
    },
  ],
  preferences: {
    ...DEFAULT_PREFERENCES,
    updatedAt: "2026-04-24T09:00:00.000Z",
  },
  projects: [
    {
      createdAt: "2026-04-24T09:00:00.000Z",
      description: "Playwright 自动化测试用项目。",
      id: "project-qa-demo",
      manualProgressNote: "",
      manualProgressOverride: null,
      name: "品牌升级",
      updatedAt: "2026-04-24T09:00:00.000Z",
    },
    {
      createdAt: "2026-04-28T08:30:00.000Z",
      description: "收敛首页、焦点卡片和任务详情的交互层级。",
      id: "project-product-polish",
      manualProgressNote: "",
      manualProgressOverride: null,
      name: "产品体验收敛",
      updatedAt: "2026-04-28T10:20:00.000Z",
    },
    {
      createdAt: "2026-04-28T08:45:00.000Z",
      description: "把日报、周报和完成任务摘要串成稳定流程。",
      id: "project-report-automation",
      manualProgressNote: "",
      manualProgressOverride: null,
      name: "报告自动化",
      updatedAt: "2026-04-28T10:10:00.000Z",
    },
    {
      createdAt: "2026-04-28T09:00:00.000Z",
      description: "统一本地存储、导入导出和测试数据策略。",
      id: "project-data-safety",
      manualProgressNote: "",
      manualProgressOverride: null,
      name: "数据安全与迁移",
      updatedAt: "2026-04-28T09:55:00.000Z",
    },
    {
      createdAt: "2026-04-28T09:20:00.000Z",
      description: "把移动端查看、快速编辑和一屏浏览做得更稳。",
      id: "project-mobile-review",
      manualProgressNote: "",
      manualProgressOverride: null,
      name: "移动端复核",
      updatedAt: "2026-04-28T09:40:00.000Z",
    },
  ],
  reports: [
    {
      createdAt: "2026-04-29T09:10:00.000Z",
      draft: {
        blockers: ["报告中心层级入口仍需统一到平台标准。"],
        completedItems: [
          "完成任务数据来源梳理",
          "收敛首页信息密度",
          "确认报告生成后的编辑保存链路",
        ],
        keyChanges: ["报告记录按月、周、日沉淀", "保留结构化草稿与最终正文两段"],
        nextSteps: ["补充复制 Markdown 入口", "复核空态与有数据态的视觉一致性"],
        overview: "今日围绕报告中心做小模块收敛，重点是让完成任务可以沉淀为可编辑报告。",
      },
      id: "report-daily-2026-04-29",
      polishedContent:
        "## Daily · 2026/04/29\n\n今日主要完成报告中心的信息结构收敛：报告从完成任务中提取，进入月、周、日层级，并保留结构化草稿与最终正文。下一步重点是复制与导出体验。",
      rangeEnd: "2026-04-29T23:59:59.999Z",
      rangeStart: "2026-04-29T00:00:00.000Z",
      sourceTaskIds: [
        "task-report-source",
        "task-polish-home-density",
        "task-data-storage-consistency",
      ],
      title: "日报 · 2026/04/29",
      type: "daily",
      updatedAt: "2026-04-29T09:40:00.000Z",
    },
    {
      createdAt: "2026-04-28T18:20:00.000Z",
      draft: {
        blockers: ["弹窗动作和颜色配置还需要继续统一。"],
        completedItems: ["完成报告数据链路验证", "首页工作台信息层级更清楚"],
        keyChanges: ["完成任务摘要字段稳定", "日报来源过滤只读取已完成任务"],
        nextSteps: ["继续整理周报模板", "补一轮视觉回归测试"],
        overview: "围绕产品体验收敛与报告自动化做验证，确认日报可从完成任务生成。",
      },
      id: "report-daily-2026-04-28",
      polishedContent:
        "## Daily · 2026/04/28\n\n今日完成报告数据链路验证，并同步收敛首页信息密度。当前阻塞主要在设置弹窗与报告中心的视觉标准统一上。",
      rangeEnd: "2026-04-28T23:59:59.999Z",
      rangeStart: "2026-04-28T00:00:00.000Z",
      sourceTaskIds: ["task-report-source", "task-polish-home-density"],
      title: "日报 · 2026/04/28",
      type: "daily",
      updatedAt: "2026-04-28T18:25:00.000Z",
    },
    {
      createdAt: "2026-04-27T18:10:00.000Z",
      draft: {
        blockers: [],
        completedItems: ["补充周报结构", "整理完成事项与关键阻塞"],
        keyChanges: ["报告草稿字段拆成概览、完成事项、关键改动、阻塞、后续动作"],
        nextSteps: ["把报告草稿和最终正文并排展示"],
        overview: "完成报告草稿结构准备，为后续日报和周报生成打基础。",
      },
      id: "report-daily-2026-04-27",
      polishedContent:
        "## Daily · 2026/04/27\n\n今日主要补齐报告草稿结构，让后续报告生成有稳定字段可以承载。",
      rangeEnd: "2026-04-27T23:59:59.999Z",
      rangeStart: "2026-04-27T00:00:00.000Z",
      sourceTaskIds: ["task-complete"],
      title: "日报 · 2026/04/27",
      type: "daily",
      updatedAt: "2026-04-27T18:12:00.000Z",
    },
    {
      createdAt: "2026-04-29T10:00:00.000Z",
      draft: {
        blockers: ["需要继续压缩报告中心模块边界，避免变成复杂分析页。"],
        completedItems: ["报告数据来源梳理", "日报草稿结构验证", "层级报告库原型完成"],
        keyChanges: ["按 Month / Week / Daily 建立报告沉淀结构"],
        nextSteps: ["补复制 Markdown", "确认月报生成入口是否需要更靠近月份节点"],
        overview: "本周重点是把完成任务沉淀为可复用报告，并让报告中心成为小型输出台。",
      },
      id: "report-weekly-2026-w18",
      polishedContent:
        "## Weekly · 2026-W18\n\n本周围绕报告自动化和产品体验收敛推进。报告中心已经具备生成、分层查看、编辑保存的基础能力，下一步补齐复制与导出。",
      rangeEnd: "2026-05-03T23:59:59.999Z",
      rangeStart: "2026-04-27T00:00:00.000Z",
      sourceTaskIds: [
        "task-report-source",
        "task-polish-home-density",
        "task-complete",
      ],
      title: "周报 · 2026-W18",
      type: "weekly",
      updatedAt: "2026-04-29T10:05:00.000Z",
    },
    {
      createdAt: "2026-04-29T10:20:00.000Z",
      draft: {
        blockers: ["导出样式与复制格式还没有定稿。"],
        completedItems: ["完成首页、焦点、任务详情和报告中心的核心体验收敛"],
        keyChanges: ["报告中心从平铺列表升级为月周日层级"],
        nextSteps: ["做 Markdown 导出", "增加报告复制后的成功反馈"],
        overview: "四月主要围绕个人任务工作台做产品体验统一，报告中心成为完成任务后的输出层。",
      },
      id: "report-monthly-2026-04",
      polishedContent:
        "## Monthly · 2026-04\n\n四月完成个人任务工作台的多处体验收敛：焦点卡片、任务详情、设置弹窗和报告中心逐步统一为更简洁的工具型界面。",
      rangeEnd: "2026-04-30T23:59:59.999Z",
      rangeStart: "2026-04-01T00:00:00.000Z",
      sourceTaskIds: [
        "task-report-source",
        "task-polish-home-density",
        "task-complete",
        "task-data-storage-consistency",
      ],
      title: "月报 · 2026-04",
      type: "monthly",
      updatedAt: "2026-04-29T10:30:00.000Z",
    },
  ],
  tasks: [
    {
      body: "",
      checklist: [
        {
          done: false,
          id: "c1",
          text: "梳理当前页面视觉语言并确认边框阴影文字大小的统一标准，避免展示层继续漂移。",
        },
        {
          done: false,
          id: "c2",
          text: "补充焦点交互设计，确认点击拖拽完成移出焦点这些动作之间不会互相冲突。",
        },
        {
          done: true,
          id: "c3",
          text: "检查任务详情区是否还存在像小型表单一样的阅读负担，并拆掉多余提示。",
        },
        {
          done: false,
          id: "c4",
          text: "补一轮视觉回归测试，确认长标题和长 Tasklist 文本不会把卡片撑坏。",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-24T09:00:00.000Z",
      id: "task-long-title",
      notes: "",
      priority: "urgent",
      progressLog: [],
      projectId: "project-qa-demo",
      status: "in_progress",
      title:
        "这是一个非常长的焦点任务标题，用来检查标题在方卡中是否会换行但不撑高整个卡片结构，同时还能保持底部操作区稳定",
      updatedAt: "2026-04-24T09:00:00.000Z",
    },
    {
      body: "",
      checklist: [
        {
          done: false,
          id: "c5",
          text: "等产品确认首页最终口径",
        },
        {
          done: false,
          id: "c6",
          text: "等设计给出最终 icon 套件",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-24T09:00:00.000Z",
      id: "task-blocked",
      notes: "",
      priority: "important",
      progressLog: [],
      projectId: "project-qa-demo",
      status: "blocked",
      title: "确认首页 CTA 口径",
      updatedAt: "2026-04-24T09:00:00.000Z",
    },
    {
      body: "",
      checklist: [
        {
          done: true,
          id: "c7",
          text: "整理完成事项",
        },
        {
          done: true,
          id: "c8",
          text: "整理关键阻塞",
        },
        {
          done: true,
          id: "c9",
          text: "整理后续动作",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-24T09:00:00.000Z",
      id: "task-complete",
      notes: "",
      priority: "normal",
      progressLog: [],
      projectId: "project-qa-demo",
      status: "todo",
      title: "补周报结构",
      updatedAt: "2026-04-24T09:00:00.000Z",
    },
    {
      body: "确认首页不再像任务详情页，优先突出当天执行节奏。",
      checklist: [
        {
          done: true,
          id: "c10",
          text: "压缩首页解释文案",
        },
        {
          done: false,
          id: "c11",
          text: "复查项目卡片操作区",
        },
      ],
      completionWrapUp: {
        completedAt: "2026-04-28T10:20:00.000Z",
        keyChanges: "首页文案和入口已收敛",
        notes: "",
        summary: "首页已更接近一屏工作台。",
      },
      createdAt: "2026-04-28T08:35:00.000Z",
      id: "task-polish-home-density",
      notes: "",
      priority: "important",
      progressLog: [],
      projectId: "project-product-polish",
      status: "done",
      title: "收敛首页信息密度",
      updatedAt: "2026-04-28T10:20:00.000Z",
    },
    {
      body: "检查焦点卡片标题、Tasklist 和底部操作是否稳定。",
      checklist: [
        {
          done: true,
          id: "c12",
          text: "长标题省略与固定高度",
        },
        {
          done: true,
          id: "c13",
          text: "Tasklist 仅预览三条",
        },
        {
          done: false,
          id: "c14",
          text: "拖拽排序手感复核",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-28T08:55:00.000Z",
      id: "task-polish-focus-card",
      notes: "",
      priority: "urgent",
      progressLog: [],
      projectId: "project-product-polish",
      status: "in_progress",
      title: "复核焦点卡片结构",
      updatedAt: "2026-04-28T10:05:00.000Z",
    },
    {
      body: "把任务详情弹窗里的关闭、保存和报错按钮统一到同一套 action 规范。",
      checklist: [
        {
          done: false,
          id: "c15",
          text: "统一信号灯颜色",
        },
        {
          done: false,
          id: "c16",
          text: "确认底部动作布局",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-28T09:10:00.000Z",
      id: "task-polish-modal-actions",
      notes: "",
      priority: "normal",
      progressLog: [],
      projectId: "project-product-polish",
      status: "todo",
      title: "统一弹窗动作风格",
      updatedAt: "2026-04-28T09:30:00.000Z",
    },
    {
      body: "把完成任务自动进入报告草稿的逻辑梳理清楚。",
      checklist: [
        {
          done: true,
          id: "c17",
          text: "确认完成任务字段",
        },
        {
          done: true,
          id: "c18",
          text: "确认日报来源过滤",
        },
      ],
      completionWrapUp: {
        completedAt: "2026-04-28T09:50:00.000Z",
        keyChanges: "完成任务摘要字段稳定",
        notes: "后续补导出样式。",
        summary: "报告数据链路已可验证。",
      },
      createdAt: "2026-04-28T08:50:00.000Z",
      id: "task-report-source",
      notes: "",
      priority: "important",
      progressLog: [],
      projectId: "project-report-automation",
      status: "done",
      title: "梳理报告数据来源",
      updatedAt: "2026-04-28T09:50:00.000Z",
    },
    {
      body: "让报告中心的生成、编辑、保存状态更容易验证。",
      checklist: [
        {
          done: false,
          id: "c19",
          text: "补充空状态",
        },
        {
          done: false,
          id: "c20",
          text: "确认保存反馈",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-28T09:15:00.000Z",
      id: "task-report-center-state",
      notes: "",
      priority: "normal",
      progressLog: [],
      projectId: "project-report-automation",
      status: "in_progress",
      title: "复核报告中心状态",
      updatedAt: "2026-04-28T10:10:00.000Z",
    },
    {
      body: "保证 demo 数据、真实本地数据和自动化浏览器看到的是同一套入口。",
      checklist: [
        {
          done: true,
          id: "c21",
          text: "确认 DEV 自动 seed",
        },
        {
          done: false,
          id: "c22",
          text: "确认导入导出后不丢字段",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-28T09:05:00.000Z",
      id: "task-data-storage-consistency",
      notes: "",
      priority: "urgent",
      progressLog: [],
      projectId: "project-data-safety",
      status: "in_progress",
      title: "统一存储验证口径",
      updatedAt: "2026-04-28T09:55:00.000Z",
    },
    {
      body: "检查历史 snapshot 的字段版本，避免老数据升级失败。",
      checklist: [
        {
          done: false,
          id: "c23",
          text: "检查 project 字段默认值",
        },
        {
          done: false,
          id: "c24",
          text: "检查 focus order 默认值",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-28T09:25:00.000Z",
      id: "task-data-import-guard",
      notes: "",
      priority: "important",
      progressLog: [],
      projectId: "project-data-safety",
      status: "blocked",
      title: "补导入兼容检查",
      updatedAt: "2026-04-28T09:45:00.000Z",
    },
    {
      body: "用窄屏检查首页项目卡片、焦点网格和任务详情弹窗。",
      checklist: [
        {
          done: false,
          id: "c25",
          text: "检查首页两栏断点",
        },
        {
          done: false,
          id: "c26",
          text: "检查项目卡片按钮命中区",
        },
        {
          done: false,
          id: "c27",
          text: "检查任务详情弹窗高度",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-28T09:30:00.000Z",
      id: "task-mobile-home-review",
      notes: "",
      priority: "normal",
      progressLog: [],
      projectId: "project-mobile-review",
      status: "todo",
      title: "移动端首页走查",
      updatedAt: "2026-04-28T09:40:00.000Z",
    },
    {
      body: "确认项目推进页在手机宽度下不会出现横向滚动。",
      checklist: [
        {
          done: false,
          id: "c28",
          text: "复核项目切换器换行",
        },
        {
          done: false,
          id: "c29",
          text: "复核任务列滚动",
        },
      ],
      completionWrapUp: null,
      createdAt: "2026-04-28T09:35:00.000Z",
      id: "task-mobile-project-review",
      notes: "",
      priority: "normal",
      progressLog: [],
      projectId: "project-mobile-review",
      status: "todo",
      title: "移动端项目页走查",
      updatedAt: "2026-04-28T09:35:00.000Z",
    },
  ],
  version: 1,
};
